### ISSUE TITLE
Build a high-level data access API for ECEPhys data

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#20]
A low-level data access and caching API is available from PR #19. We need a new high-level data access and analysis API for the ECEPhys data, to complement the existing high-level OPhys data access API in `bot.ophyssession`.

This work will go in branch `dev/ecphys_highlevel` https://github.com/emeyers/Brain-Observatory-Toolbox/tree/dev/ecphys_highlevel

# Tasks
1. [x] Draft a high-level API class including methods and properties from the Allen SDK classes in Python `brain_observatory.ecephys.ecephys_session` class
2. [ ] Implement the data access methods
3. [ ] Refactor `bot.ophyssession` -> superclass `bot.session`, `bot.ecephyssession` should inherit from `bot.session` when possible
3. [ ] Implement caching of data access using matlab `memoize` function
4. [ ] Verify functionality against Allen SDK
5. [ ] Unit testing for all data access methods in `bot.test`
6. [ ] Inline docs for all properties and methods
----
7. [ ] Add a "quick start" guide for the EPhys data
8. [ ] Add a tutorial for the EPhys data

**Comment by DylanMuir** [comment]
Close, won't complete.
